version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - UNSPLASH_CLIENT_ID=01NaKsZIj_hfxDAHQ8XhFdiMgZomw97WXjgJRzTBrW4
      - UNSPLASH_CLIENT_SECRET=_YDtSUV07C6FgoVJbKvP6rM8EjLVYa9nvSWQCmdwIiE
      - REDIRECT_URI=http://localhost:3000/auth/unsplash/callback
      - SESSION_SECRET=667263
      - PORT=3000

volumes:
  db_data: