version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"  # Cambiado a puerto 3000 que es más común en Node.js
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  db_data: